const saved=JSON.parse(localStorage.getItem('trial-workbench')||'{}');
const state={trials:[],selected:null,view:null,total:0,offset:saved.offset||0,limit:10,filters:saved.filters||{},selectedId:saved.selectedId||new URLSearchParams(location.search).get('trial')};
const $=s=>document.querySelector(s);
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const status=s=>({DRAFT:'方案待锁定',PROTOCOL_LOCKED:'待登记老化条件',EXPOSURE_RECORDED:'待提交计数',COUNTING:'计数与偏差复核',REVIEWED:'质量门禁待签发',RELEASED:'待封存',ARCHIVED:'已封存'})[s]||s;
async function api(path,options={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const data=await r.json();if(!r.ok)throw new Error(data.message||'请求失败');return data}
function persist(){localStorage.setItem('trial-workbench',JSON.stringify({filters:state.filters,offset:state.offset,selectedId:state.selectedId}));const u=new URL(location);state.selectedId?u.searchParams.set('trial',state.selectedId):u.searchParams.delete('trial');history.replaceState(null,'',u)}
function request(actor,role){return{request_id:crypto.randomUUID(),expected_revision:state.selected.revision,actor,role}}
function query(){const p=new URLSearchParams({...state.filters,offset:state.offset,limit:state.limit});for(const [k,v] of [...p])if(!v)p.delete(k);return p}
async function load(){const data=await api('/api/trials?'+query());state.trials=data.trials||[];state.total=data.total;renderList(data.summary);if(state.selectedId){try{await select(state.selectedId,false)}catch{state.selected=null;state.view=null;state.selectedId=null;persist();renderEmpty()}}}
function renderList(summary){$('#trialList').innerHTML=state.trials.map(t=>`<button class="trial ${state.selectedId===t.id?'active':''}" data-id="${esc(t.id)}"><b>${esc(t.seed_lot_code)}</b><small>${esc(t.crop_name)} · ${status(t.status)}</small></button>`).join('')||'<div class="readonly">没有匹配批次</div>';document.querySelectorAll('.trial').forEach(b=>b.onclick=()=>select(b.dataset.id));$('#summary').textContent=`命中 ${state.total} · 缺失轮次 ${summary.missing_rounds} · 未决偏差 ${summary.open_deviations}`;$('#pageInfo').textContent=`${Math.floor(state.offset/state.limit)+1} / ${Math.max(1,Math.ceil(state.total/state.limit))}`;$('#prevPage').disabled=state.offset===0;$('#nextPage').disabled=state.offset+state.limit>=state.total}
async function select(id,save=true){state.view=await api(`/api/trials/${id}/view`);state.selected=state.view.trial;state.selectedId=id;if(save)persist();renderListSelection();render()}
function renderListSelection(){document.querySelectorAll('.trial').forEach(b=>b.classList.toggle('active',b.dataset.id===state.selectedId))}
function renderEmpty(){$('#workspace').innerHTML='<div class="empty"><strong>选择一个复核批次</strong><p>查看试验方案、条件、计数、门禁与审计记录。</p></div>'}
function metric(label,value){return `<div class="metric"><small>${label}</small><b>${value}</b></div>`}
function render(){const t=state.selected,v=state.view,p=v.progress;$('#workspace').innerHTML=`<div class="topline"><div><h2>${esc(t.seed_lot_code)} · ${esc(t.crop_name)}</h2><small>${esc(t.id)} / 负责人 ${esc(t.owner)} / 修订 ${t.revision}</small></div><span class="status">${status(t.status)}</span></div><div class="grid">${metric('流程完成度',p.percent+'%')}${metric('已提交计数',p.submitted_rounds+'/'+p.expected_rounds)}${metric('待裁决偏差',p.open_deviations)}${metric('已登记条件',p.exposure_groups+'/'+p.total_groups)}</div>${step(t,v)}${countTable(t)}${deviations(t)}${audit(t)}`;bind(t)}
function protocolStep(t){return `<div class="panel"><h3>试验方案锁定前影响预检</h3><form class="inline" id="protocol"><label>样本量<input name="sample_size" type="number" value="100" required></label><label>老化温度 °C<input name="aging_temp_c" type="number" value="41" step="0.1" required></label><label>老化湿度 %<input name="aging_humidity" type="number" value="75" step="0.1" required></label><label>萌发判定日<input name="judgement_date" type="date" required></label><label>计数轮次<input name="rounds" type="number" value="1" required></label><label>放行阈值 %<input name="threshold" type="number" value="80" required></label><button>预检方案</button></form><div id="preflight"></div></div>`}
function exposureStep(t,v){return `<div class="panel"><h3>登记老化条件快照</h3><div class="chips">${v.recorded_exposure_groups.map(g=>`<span class="chip">已登记 ${esc(g)}</span>`).join('')}${v.pending_exposure_groups.map(g=>`<span class="chip">待登记 ${esc(g)}</span>`).join('')}</div><form class="inline" id="exposure"><label>样本分组<select name="group_code">${v.pending_exposure_groups.map(g=>`<option>${esc(g)}</option>`).join('')}</select></label><label>开始时间<input name="started_at" type="datetime-local" required></label><label>结束时间<input name="ended_at" type="datetime-local" required></label><label>设备编号<input name="device" required></label><label>设备温度 °C<input name="temperature_c" type="number" step="0.1" required></label><label>设备湿度 %<input name="humidity" type="number" step="0.1" required></label><label>操作人<input name="operator" required></label><label>条件证据<input name="evidence" required></label><button>保存条件快照</button></form></div>`}
function countingStep(t,v){const group=v.progress.groups.find(g=>g.next_round);if(!group)return `<div class="panel"><h3>计数完整性复核</h3><form class="inline" id="review"><label>独立复核员<input name="reviewer" required></label><button>执行复核</button></form></div>`;const base=group.previous_round?`前轮：正常 ${group.previous_round.normal_count} / 异常 ${group.previous_round.abnormal_count} / 未萌发 ${group.previous_round.ungerminated_count}`:'首轮无基线';return `<div class="panel"><h3>提交萌发计数</h3><div class="notice">${esc(group.group_code)} 下一轮 ${group.next_round}，${base}，剩余 ${group.remaining_rounds} 轮</div><form class="inline" id="round"><label>样本分组<select name="group_code">${v.progress.groups.filter(g=>g.next_round).map(g=>`<option value="${esc(g.group_code)}" data-round="${g.next_round}">${esc(g.group_code)} · 第 ${g.next_round} 轮</option>`).join('')}</select></label><input name="round_no" type="hidden" value="${group.next_round}"><label>正常苗<input name="normal_count" type="number" min="0" required></label><label>异常苗<input name="abnormal_count" type="number" min="0" required></label><label>未萌发<input name="ungerminated_count" type="number" min="0" required></label><label>操作人<input name="operator" required></label><label>证据说明<input name="evidence_note"></label><button>提交计数</button></form></div>`}
function gateStep(t,v){return `<div class="panel"><h3>质量门禁与职责分离</h3><div id="gateReport">${gateReport(v.gate)}</div><form class="inline" id="gate"><label>签发负责人<input name="signer" required></label><button type="button" id="previewGate">预览门禁</button><button>签发放行决定</button></form></div>`}
function gateReport(g){return `<div class="chips"><span class="chip">完整性 ${g.completeness?'通过':'阻断'}</span><span class="chip">阈值 ${g.threshold_satisfied?'通过':'阻断'}</span><span class="chip">偏差终态 ${g.deviation_final?'通过':'阻断'}</span><span class="chip">职责分离 ${g.separation_satisfied?'通过':'阻断'}</span></div>${(g.blocks||[]).map(b=>`<div class="notice error"><b>${esc(b.code)}</b> ${esc(b.message)}<small>${esc(b.remediation)}</small></div>`).join('')}`}
function archiveStep(t){if(t.status==='RELEASED')return `<div class="panel"><h3>签署封存</h3><form class="inline" id="archive"><label>签署人<input name="actor" required></label><button>确认封存</button></form></div>`;return `<div class="panel"><h3>不可变归档证明</h3><div class="readonly">归档摘要：${esc(t.archive_digest)}</div><button id="verifyArchive">执行完整性核验</button><div id="proof"></div></div>`}
function step(t,v){if(t.status==='DRAFT')return protocolStep(t);if(t.status==='PROTOCOL_LOCKED')return exposureStep(t,v);if(t.status==='EXPOSURE_RECORDED'||t.status==='COUNTING')return countingStep(t,v);if(t.status==='REVIEWED')return gateStep(t,v);return archiveStep(t)}
function countTable(t){if(!t.rounds.length)return'';return `<div class="panel"><h3>分轮计数与版本</h3><table class="table"><thead><tr><th>分组/轮次</th><th>正常/异常/未萌发</th><th>活力率</th><th>操作</th></tr></thead><tbody>${t.rounds.map(r=>{const history=t.count_corrections.filter(c=>c.group_code===r.group_code&&c.round_no===r.round_no);return `<tr><td>${esc(r.group_code)} / ${r.round_no}</td><td>${r.normal_count} / ${r.abnormal_count} / ${r.ungerminated_count}${history.length?`<details><summary>展开 ${history.length} 次更正</summary>${history.map(c=>`<small>${new Date(c.at).toLocaleString()} · ${esc(c.actor)} · ${esc(c.reason)}<br>原值 ${c.before.normal_count}/${c.before.abnormal_count}/${c.before.ungerminated_count} → 新值 ${c.after.normal_count}/${c.after.abnormal_count}/${c.after.ungerminated_count} · ${esc(c.evidence)}</small>`).join('<hr>')}</details>`:''}</td><td>${r.vigor_rate.toFixed(1)}%</td><td class="row-actions">${t.status==='COUNTING'?`<button class="correct" data-group="${esc(r.group_code)}" data-round="${r.round_no}">更正</button>`:''}<small>版本 ${1+history.length}</small></td></tr>`}).join('')}</tbody></table></div>`}
function deviations(t){if(!t.deviations.length)return'';return `<div class="panel"><h3>偏差裁决与整改</h3>${t.deviations.map(d=>`<div class="readonly"><b>${esc(d.kind)}</b> · ${esc(d.severity)} · ${esc(d.stage||'PENDING_REVIEW')}<p>${d.group_code?`分组 ${esc(d.group_code)} · `:''}${d.device?`设备 ${esc(d.device)} · `:''}${d.measured!==undefined?`实测 ${d.measured} / 边界 ${d.lower_bound}–${d.upper_bound}`:''}</p>${(d.decisions||[]).map(x=>`<small>裁决 ${esc(x.decision)} · ${esc(x.reviewer)} · ${new Date(x.at).toLocaleString()}</small>`).join('<br>')}${deviationAction(d)}</div>`).join('')}</div>`}
function deviationAction(d){const versions=(d.remediations||[]).length?`<details><summary>展开整改版本</summary>${d.remediations.map(x=>`<small>${new Date(x.at).toLocaleString()} · ${esc(x.actor)} · ${esc(x.root_cause)} · ${esc(x.disposition)} · ${esc(x.evidence)}</small>`).join('<br>')}</details>`:'';if(d.stage==='REMEDIATION_REQUIRED')return `${versions}<form class="inline remediation" data-id="${esc(d.id)}" data-reporter="${esc(d.reported_by)}"><label>新根因<input name="root_cause" required></label><label>处置说明<input name="disposition" required></label><label>证据引用<input name="evidence" required></label><button>提交整改</button></form>`;if(d.stage==='ACCEPTED')return versions;return `${versions}<form class="inline deviation" data-id="${esc(d.id)}"><label>原因分析<input name="root_cause" required></label><label>处置意见<input name="disposition" required></label><label>复核员<input name="reviewer" required></label><label>裁决<select name="decision"><option value="ACCEPTED">接受处置</option><option value="REJECTED">退回整改</option></select></label><button>提交裁决</button></form>`}
function audit(t){return `<div class="panel"><h3>审计时间线</h3><form class="inline" id="auditFilter"><label>事件类型<input name="type"></label><label>操作者<input name="actor"></label><label>开始时间<input name="from" type="datetime-local"></label><label>结束时间<input name="to" type="datetime-local"></label><button>筛选时间线</button></form><div class="timeline" id="timeline">${events(t.audit)}</div></div>`}
function events(xs){return xs.slice().reverse().map(e=>`<div class="event"><b>${esc(e.type)}</b><small>${new Date(e.at).toLocaleString()} · ${esc(e.actor)} · rev ${e.revision}</small></div>`).join('')}
function formBody(form){return Object.fromEntries(new FormData(form).entries())}
function auditBody(form){const value=formBody(form);for(const field of ['from','to'])value[field]=value[field]?new Date(value[field]).toISOString():'';return value}
function numeric(x,names){names.forEach(k=>x[k]=Number(x[k]));return x}
async function send(path,method,payload){try{state.selected=await api(path,{method,body:JSON.stringify(payload)});state.selectedId=state.selected.id;await load()}catch(e){alert(e.message)}}
function bind(t){const p=$('#protocol');if(p)p.onsubmit=async e=>{e.preventDefault();const v=numeric(formBody(p),['sample_size','aging_temp_c','aging_humidity','rounds','threshold']);try{const pre=await api(`/api/trials/${t.id}/protocol/preflight`,{method:'POST',body:JSON.stringify({...v,...request('负责人','LEAD')})});$('#preflight').innerHTML=`<div class="notice ${pre.blocking_issues.length?'error':''}">预计 ${pre.expected_count_records} 条计数记录 · 温度 ${pre.temperature_range.minimum}–${pre.temperature_range.maximum} °C · 湿度 ${pre.humidity_range.minimum}–${pre.humidity_range.maximum}%${pre.judgement_before_trial?' · 判定日早于批次创建日':''}</div>`;if(!pre.blocking_issues.length&&confirm('预检通过，确认锁定方案？'))send(`/api/trials/${t.id}/protocol`,'PUT',{...v,preflight_summary:pre.summary,...request('负责人','LEAD')})}catch(err){alert(err.message)}};const x=$('#exposure');if(x)x.onsubmit=e=>{e.preventDefault();const v=numeric(formBody(x),['temperature_c','humidity']);v.started_at=new Date(v.started_at).toISOString();v.ended_at=new Date(v.ended_at).toISOString();send(`/api/trials/${t.id}/exposures`,'POST',{...v,...request(v.operator,'TECHNICIAN')})};const r=$('#round');if(r){r.group_code.onchange=()=>{const option=r.group_code.selectedOptions[0];r.round_no.value=option.dataset.round};r.onsubmit=e=>{e.preventDefault();const v=numeric(formBody(r),['round_no','normal_count','abnormal_count','ungerminated_count']);send(`/api/trials/${t.id}/rounds`,'POST',{...v,...request(v.operator,'TECHNICIAN')})}}const rv=$('#review');if(rv)rv.onsubmit=e=>{e.preventDefault();const v=formBody(rv);send(`/api/trials/${t.id}/review`,'POST',{...v,...request(v.reviewer,'REVIEWER')})};bindGate(t);const ar=$('#archive');if(ar)ar.onsubmit=e=>{e.preventDefault();const v=formBody(ar);send(`/api/trials/${t.id}/archive`,'POST',{...request(v.actor,'LEAD')})};const verify=$('#verifyArchive');if(verify)verify.onclick=async()=>{try{const p=await api(`/api/trials/${t.id}/integrity`);$('#proof').innerHTML=p.checks.map(c=>`<div class="notice ${c.passed?'':'error'}"><b class="${c.passed?'proof-pass':'proof-fail'}">${esc(c.name)} · ${c.passed?'通过':'失败'}</b><small>${esc(c.message)}</small></div>`).join('')}catch(e){alert(e.message)}};bindRows(t);const af=$('#auditFilter');if(af)af.onsubmit=async e=>{e.preventDefault();try{const d=await api(`/api/trials/${t.id}/audit?`+new URLSearchParams({...auditBody(af),offset:0,limit:50}));$('#timeline').innerHTML=events(d.events)}catch(err){alert(err.message)}}}
function bindGate(t){const g=$('#gate');if(!g)return;$('#previewGate').onclick=async()=>{try{$('#gateReport').innerHTML=gateReport(await api(`/api/trials/${t.id}/gate?signer=${encodeURIComponent(g.signer.value)}`))}catch(e){alert(e.message)}};g.onsubmit=e=>{e.preventDefault();send(`/api/trials/${t.id}/release`,'POST',{...request(g.signer.value,'LEAD')})}}
function bindRows(t){document.querySelectorAll('.correct').forEach(b=>b.onclick=()=>{const round=t.rounds.find(r=>r.group_code===b.dataset.group&&r.round_no===Number(b.dataset.round));const normal=prompt('更正后正常苗',round.normal_count);if(normal===null)return;const abnormal=prompt('更正后异常苗',round.abnormal_count);if(abnormal===null)return;const ungerminated=prompt('更正后未萌发',round.ungerminated_count);if(ungerminated===null)return;const actor=prompt('更正人');const reason=prompt('更正原因');const evidence=prompt('证据说明');if(actor&&reason&&evidence)send(`/api/trials/${t.id}/rounds/correction`,'POST',{group_code:round.group_code,round_no:round.round_no,normal_count:Number(normal),abnormal_count:Number(abnormal),ungerminated_count:Number(ungerminated),reason,evidence,...request(actor,'TECHNICIAN')})});document.querySelectorAll('.deviation').forEach(f=>f.onsubmit=e=>{e.preventDefault();const v=formBody(f);send(`/api/trials/${t.id}/deviations/${f.dataset.id}/review`,'POST',{...v,...request(v.reviewer,'REVIEWER')})});document.querySelectorAll('.remediation').forEach(f=>f.onsubmit=e=>{e.preventDefault();const v=formBody(f);send(`/api/trials/${t.id}/deviations/${f.dataset.id}/remediation`,'POST',{...v,...request(f.dataset.reporter,'TECHNICIAN')})})}
const filters=$('#filters');for(const [k,v] of Object.entries(state.filters))if(filters.elements[k])filters.elements[k].value=v;filters.onsubmit=e=>{e.preventDefault();state.filters=formBody(filters);state.offset=0;persist();load()};$('#clearFilters').onclick=()=>{filters.reset();state.filters={};state.offset=0;persist();load()};$('#prevPage').onclick=()=>{state.offset=Math.max(0,state.offset-state.limit);persist();load()};$('#nextPage').onclick=()=>{state.offset+=state.limit;persist();load()};$('#refresh').onclick=load;$('#newTrial').onclick=()=>$('#createDialog').showModal();$('#createForm').onsubmit=async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const v=formBody(e.currentTarget);v.groups=v.groups.split(',').map(x=>x.trim()).filter(Boolean);try{const t=await api('/api/trials',{method:'POST',body:JSON.stringify({...v,actor:v.owner,role:'TECHNICIAN',request_id:crypto.randomUUID()})});state.selectedId=t.id;state.offset=0;$('#createDialog').close();persist();await load()}catch(err){alert(err.message)}};load();
